### ISSUE TITLE
ลองใช้งานไม่ได้

### ISSUE THREAD

**Issue by gamemun01** [positronth/bxgo.io#1]
ใส่ API กับ Key แล้ว
มันเข้าไม่ได้ครับมันขึ้นว่า 
ERROR - Message:api_balance - Unmarshal - invalid character 'I' looking for beginning of value{"success":false,"error":Invalid API Key}

**Comment by mositron** [comment]
"Invalid API Key" ในข้อความ error คือ key/secret ผิดครับ

ลองเช็ค key/secret ที่เอามาจาก bx.in.th ดูครับว่าตรงหรือเปล่า ถ้าตรงแล้วแต่ยังไม่ได้ให้สร้างคีย์ใหม่ดู
