### ISSUE TITLE
รัน v. 0.5.0 แล้วเด้งครับ 0.4.7 ใช้งานได้ปกติ

### ISSUE THREAD

**Issue by panapornk** [positronth/bxgo.io#2]
> #####################################################
BXGo v. 0.5.0
Time: Sep 26 20:19:13
Web Listen: 8000
#####################################################
panic: time: missing Location in call to Time.In

goroutine 7 [running]:
panic(0x70b8c0, 0xc08222a2b0)
        /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3f4
time.Time.In(0xed15c4ad1, 0x2b622da4, 0x9fae20, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go-1.6/src/time/time.go:803 +0x8c
main.api_pair()
        /mnt/d/Go/src/bxgo/app/api.go:64 +0x427
main.main.func2()
        /mnt/d/Go/src/bxgo/app/main.go:53 +0x1b
created by main.main
        /mnt/d/Go/src/bxgo/app/main.go:54 +0x7a6

>

**Comment by mositron** [comment]
แก้ไขในเวอร์ชั่น 0.5.1 แล้วครับ
สามารถดาวน์โหลดได้เลย
